#!/usr/bin/docker-compose -f

name: anki-card
services:
  make:
    build: .
    entrypoint: "gmake"
    volumes:
      - .:/work
      - node_modules:/work/node_modules
  gen:
    build: .
    entrypoint: "./anki-card.js"
    volumes:
      - .:/work
      - node_modules:/work/node_modules
volumes:
  node_modules:
